-- dt = #{DateUtil.format(DateUtil.addHours(Job.planTime,-1),'yyyy-MM-dd')}
-- hour = #{DateUtil.format(DateUtil.addHours(Job.planTime,-1),'HH')}
-- env = prod

-- prod_ods.ods_mip_author_raw to prod_dwd.dwd_mip_author_detail_inc_hourly

INSERT OVERWRITE TABLE ${env}_dwd.dwd_mip_author_detail_inc_hourly PARTITION (dt, hour)
SELECT get_json_object(data, '$.data._id')                          _id,
       get_json_object(data, '$.data.source')                       source,
       get_json_object(data, '$.data.type')                         type,
       get_json_object(data, '$.data.id')                           id,
       get_json_object(data, '$.data.author_id')                    author_id,
       get_json_object(data, '$.data.avatar')                       avatar,
       get_json_object(data, '$.data.account')                      account,
       get_json_object(data, '$.data.name')                         name,
       get_json_object(data, '$.data.keyword')                      keyword,
       get_json_object(data, '$.data.user_data.identify')           identify,
       get_json_object(data, '$.data.user_data.officially')         officially,
       get_json_object(data, '$.data.user_data.officially_type')    officially_type,
       get_json_object(data, '$.data.user_data.officially_details') officially_details,
       get_json_object(data, '$.data.user_data.is_certified')       is_certified,
       get_json_object(data, '$.data.user_data.intro')              intro,
       get_json_object(data, '$.data.user_data.sign')               sign,
       get_json_object(data, '$.data.user_data.category')           category,
       get_json_object(data, '$.data.user_data.home_page')          home_page,
       get_json_object(data, '$.data.user_data.tags')               tags,
       get_json_object(data, '$.data.user_data.age')                age,
       get_json_object(data, '$.data.user_data.birthday')           birthday,
       get_json_object(data, '$.data.user_data.area')               area,
       get_json_object(data, '$.data.user_data.gender')             gender,
       get_json_object(data, '$.data.user_data.industry')           industry,
       get_json_object(data, '$.data.user_data.brand_cooperation')  brand_cooperation,
       get_json_object(data, '$.data.user_data.company')            company,
       get_json_object(data, '$.data.user_data.email')              email,
       get_json_object(data, '$.data.user_data.school')             school,
       get_json_object(data, '$.data.user_data.website')            website,
       get_json_object(data, '$.data.user_data.has_shop')           has_shop,
       get_json_object(data, '$.data.user_data.has_live')           has_live,
       get_json_object(data, '$.data.user_data.ip_location')        ip_location,
       get_json_object(data, '$.data.user_data.mcn')                mcn,
       get_json_object(data, '$.data.user_data.level')              level,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.follow_cnt')                              follow_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.fans_cnt')                                fans_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.works_cnt')                               works_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.music_cnt')                               music_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.praised_cnt')                             praised_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.forward_cnt')                             forward_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.comment_cnt')                             comment_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.time')                                    time,
       get_json_object(data, '$.data.ctime')                        ctime,
       get_json_object(data, '$.data.mtime')                        mtime,
       dt,
       hour
FROM prod_ods.ods_mip_author_raw
WHERE dt = '${dt}'
  AND hour = '${hour}';


-- prod_ods.ods_mip_article_raw to prod_dwd.dwd_mip_article_detail_inc_hourly

INSERT OVERWRITE TABLE ${env}_dwd.dwd_mip_article_detail_inc_hourly PARTITION (dt, hour)
SELECT get_json_object(data, '$.data._id')                           _id,
       get_json_object(data, '$.data.source')                        source,
       get_json_object(data, '$.data.id')                            id,
       get_json_object(data, '$.data.article_id')                    article_id,
       get_json_object(data, '$.data.author_id')                     author_id,
       get_json_object(data, '$.data.title')                         title,
       get_json_object(data, '$.data.content')                       content,
       get_json_object(data, '$.data.share_url')                     share_url,
       get_json_object(data, '$.data.keyword')                       keyword,
       get_json_object(data, '$.data.article_data.desc')             `desc`,
       get_json_object(data, '$.data.article_data.location')         location,
       get_json_object(data, '$.data.article_data.tags')             tags,
       get_json_object(data, '$.data.article_data.topic')            topic,
       get_json_object(data, '$.data.article_data.author_name')      author_name,
       get_json_object(data, '$.data.article_data.author_cover')     author_cover,
       get_json_object(data, '$.data.article_data.forward_tid')      forward_tid,
       get_json_object(data, '$.data.article_data.cover')            cover,
       get_json_object(data, '$.data.article_data.content_img_list') content_img_list,
       get_json_object(data, '$.data.article_data.post_source')      post_source,
       get_json_object(data, '$.data.article_data.relate_objects')   relate_objects,
       get_json_object(data, '$.data.article_data.source_url')       source_url,
       get_json_object(data, '$.data.article_data.words_cnt')        words_cnt,
       get_json_object(data, '$.data.article_data.play_cnt')         play_cnt,
       get_json_object(data, '$.data.article_data.video_list')       video_list,
       get_json_object(data, '$.data.article_data.video_cover_list') video_cover_list,
       get_json_object(data, '$.data.article_data.last_update_time') last_update_time,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.adorable_cnt')                             adorable_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.share_cnt')                                share_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.forward_cnt')                              forward_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.collect_cnt')                              collect_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.read_cnt')                                 read_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.click_cnt')                                click_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.comment_cnt')                              comment_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.diamond_cnt')                              diamond_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.reward_cnt')                               reward_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.down_cnt')                                 down_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.up_cnt')                                   up_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.watching_cnt')                             watching_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.time')                                     time,
       get_json_object(data, '$.data.ctime')                         ctime,
       get_json_object(data, '$.data.mtime')                         mtime,
       dt,
       hour
FROM prod_ods.ods_mip_article_raw
WHERE dt = '${dt}'
  AND hour = '${hour}';

-- prod_ods.ods_mip_media_raw to prod_dwd.dwd_mip_media_detail_inc_hourly

INSERT OVERWRITE TABLE ${env}_dwd.dwd_mip_media_detail_inc_hourly PARTITION (dt, hour)
SELECT get_json_object(data, '$.data._id')                         _id,
       get_json_object(data, '$.data.source')                      source,
       get_json_object(data, '$.data.id')                          id,
       get_json_object(data, '$.data.author_id')                   author_id,
       get_json_object(data, '$.data.media_id')                    media_id,
       get_json_object(data, '$.data.cover')                       cover,
       get_json_object(data, '$.data.title')                       title,
       get_json_object(data, '$.data.share_url')                   share_url,
       get_json_object(data, '$.data.duration')                    duration,
       get_json_object(data, '$.data.status')                      status,
       get_json_object(data, '$.data.keyword')                     keyword,
       get_json_object(data, '$.data.media_data.desc')             `desc`,
       get_json_object(data, '$.data.media_data.group_name')       group_name,
       get_json_object(data, '$.data.media_data.inner_group_name') inner_group_name,
       get_json_object(data, '$.data.media_data.topic')            topic,
       get_json_object(data, '$.data.media_data.tags')             tags,
       get_json_object(data, '$.data.media_data.activity_tags')    activity_tags,
       get_json_object(data, '$.data.media_data.related_user')     related_user,
       get_json_object(data, '$.data.media_data.bg_music')         bg_music,
       get_json_object(data, '$.data.media_data.author_name')      author_name,
       get_json_object(data, '$.data.media_data.author_cover')     author_cover,
       get_json_object(data, '$.data.media_data.author_account')   author_account,
       get_json_object(data, '$.data.media_data.media_url')        media_url,
       get_json_object(data, '$.data.media_data.media_image_url')  media_image_url,
       get_json_object(data, '$.data.media_data.media_audio_url')  media_audio_url,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.adorable_cnt')                           adorable_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.comment_cnt')                            comment_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.share_cnt')                              share_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.collect_cnt')                            collect_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.play_cnt')                               play_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.coin_cnt')                               coin_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.barrage_cnt')                            barrage_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.click_cnt')                              click_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.rank')                                   `rank`,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.time')                                   time,
       get_json_object(data, '$.data.ctime')                       ctime,
       get_json_object(data, '$.data.mtime')                       mtime,
       dt,
       hour
FROM prod_ods.ods_mip_media_raw
WHERE dt = '${dt}'
  AND hour = '${hour}';


-- prod_ods.ods_mip_comment_raw to prod_dwd.dwd_mip_comment_detail_inc_hourly

INSERT OVERWRITE TABLE ${env}_dwd.dwd_mip_comment_detail_inc_hourly PARTITION (dt, hour)
SELECT get_json_object(data, '$.data._id')                 _id,
       get_json_object(data, '$.data.source')              source,
       get_json_object(data, '$.data.id')                  id,
       get_json_object(data, '$.data.item_id')             item_id,
       get_json_object(data, '$.data.comment_pid')         comment_pid,
       get_json_object(data, '$.data.comment_id')          comment_id,
       get_json_object(data, '$.data.commentor_id')        commentor_id,
       get_json_object(data, '$.data.commentor_name')      commentor_name,
       get_json_object(data, '$.data.commentor_avatar')    commentor_avatar,
       get_json_object(data, '$.data.content')             content,

       get_json_object(data, '$.data.comment_data.device') device,

       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.adorable_cnt')                   adorable_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.down_cnt')                       down_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.comment_cnt')                    comment_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.time')                           time,
       get_json_object(data, '$.data.ctime')               ctime,
       get_json_object(data, '$.data.mtime')               mtime,
       dt,
       hour
FROM prod_ods.ods_mip_comment_raw
WHERE dt = '${dt}'
  AND hour = '${hour}';
