-- prod_ods.ods_mip_author_raw to prod_dwd.dwd_mip_author_detail_inc_hourly

INSERT OVERWRITE TABLE prod_dwd.dwd_mip_author_detail_inc_hourly PARTITION (dt, hour)
SELECT get_json_object(data, '$.data._id')                   _id,
       get_json_object(data, '$.data.source')                source,
       get_json_object(data, '$.data.type')                  type,
       get_json_object(data, '$.data.id')                    id,
       get_json_object(data, '$.data.author_id')             author_id,
       get_json_object(data, '$.data.avatar')                avatar,
       get_json_object(data, '$.data.account')               account,
       get_json_object(data, '$.data.name')                  name,
       get_json_object(data, '$.data.keyword')               keyword,
       get_json_object(data, '$.data.user_data.ip_location') ip_location,
       get_json_object(data, '$.data.user_data.level')       level,
       get_json_object(data, '$.data.user_data.intro')       intro,
       get_json_object(data, '$.data.user_data.home_page')   home_page,
       get_json_object(data, '$.data.user_data.birthday')    birthday,
       get_json_object(data, '$.data.user_data.area')        area,
       get_json_object(data, '$.data.user_data.gender')      gender,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.praised_cnt')                      praised_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.forward_cnt')                      forward_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.comment_cnt')                      comment_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.follow_cnt')                       follow_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.fans_cnt')                         fans_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.works_cnt')                        works_cnt,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.author_id')                        report_data_author_id,
       get_json_object(json_array_get_last(get_json_object(data, '$.data.report_data')),
                       '$.time')                             time,
       get_json_object(data, '$.data.ctime')                 ctime,
       get_json_object(data, '$.data.mtime')                 mtime,
       get_json_object(data, '$.data.insert_time')           insert_time,
       get_json_object(data, '$.data.page_source')           page_source,
       get_json_object(data, '$.data.is_done')               is_done,
       get_json_object(data, '$.data.storestatus')           storestatus,
       dt,
       hour
FROM prod_ods.ods_mip_author_raw
WHERE dt = '2022-10-12'
  and hour = '17'