package com.donson.udf;

public class UdfTest {



  public static void main(String[] args) {

    String s = "[\n"
        + "            {\n"
        + "                \"follow_cnt\":176,\n"
        + "                \"fans_cnt\":164,\n"
        + "                \"praised_cnt\":1076,\n"
        + "                \"time\":1646128469,\n"
        + "                \"author_id\":\"\"\n"
        + "            },\n"
        + "            {\n"
        + "                \"time\":1647590551,\n"
        + "                \"author_id\":\"\",\n"
        + "                \"follow_cnt\":173,\n"
        + "                \"fans_cnt\":167,\n"
        + "                \"praised_cnt\":1090\n"
        + "            },\n"
        + "            {\n"
        + "                \"follow_cnt\":198,\n"
        + "                \"fans_cnt\":217,\n"
        + "                \"praised_cnt\":1280,\n"
        + "                \"time\":1657384947,\n"
        + "                \"author_id\":\"\"\n"
        + "            },\n"
        + "            {\n"
        + "                \"time\":1658681583,\n"
        + "                \"author_id\":\"\",\n"
        + "                \"follow_cnt\":196,\n"
        + "                \"fans_cnt\":223,\n"
        + "                \"works_cnt\":2513,\n"
        + "                \"praised_cnt\":1337\n"
        + "            },\n"
        + "            {\n"
        + "                \"author_id\":\"\",\n"
        + "                \"follow_cnt\":184,\n"
        + "                \"fans_cnt\":262,\n"
        + "                \"works_cnt\":2697,\n"
        + "                \"praised_cnt\":1582,\n"
        + "                \"forward_cnt\":1375,\n"
        + "                \"comment_cnt\":8738,\n"
        + "                \"time\":1662480156\n"
        + "            },\n"
        + "            {\n"
        + "                \"comment_cnt\":8798,\n"
        + "                \"time\":1663164443,\n"
        + "                \"author_id\":\"\",\n"
        + "                \"follow_cnt\":187,\n"
        + "                \"fans_cnt\":269,\n"
        + "                \"works_cnt\":2728,\n"
        + "                \"praised_cnt\":1625,\n"
        + "                \"forward_cnt\":1377\n"
        + "            },\n"
        + "            {\n"
        + "                \"praised_cnt\":1696,\n"
        + "                \"forward_cnt\":1388,\n"
        + "                \"comment_cnt\":9141,\n"
        + "                \"time\":1664330429,\n"
        + "                \"author_id\":\"\",\n"
        + "                \"follow_cnt\":164,\n"
        + "                \"fans_cnt\":282,\n"
        + "                \"works_cnt\":2795\n"
        + "            },\n"
        + "            {\n"
        + "                \"fans_cnt\":287,\n"
        + "                \"works_cnt\":2798,\n"
        + "                \"praised_cnt\":1699,\n"
        + "                \"forward_cnt\":1388,\n"
        + "                \"comment_cnt\":9158,\n"
        + "                \"time\":1664463589,\n"
        + "                \"author_id\":\"\",\n"
        + "                \"follow_cnt\":164\n"
        + "            },\n"
        + "            {\n"
        + "                \"follow_cnt\":164,\n"
        + "                \"fans_cnt\":283,\n"
        + "                \"works_cnt\":2799,\n"
        + "                \"praised_cnt\":1700,\n"
        + "                \"forward_cnt\":1388,\n"
        + "                \"comment_cnt\":9188,\n"
        + "                \"time\":1664552506,\n"
        + "                \"author_id\":\"\"\n"
        + "            },\n"
        + "            {\n"
        + "                \"fans_cnt\":300,\n"
        + "                \"works_cnt\":2815,\n"
        + "                \"praised_cnt\":1745,\n"
        + "                \"forward_cnt\":1413,\n"
        + "                \"comment_cnt\":9307,\n"
        + "                \"time\":1664820987,\n"
        + "                \"author_id\":\"\",\n"
        + "                \"follow_cnt\":165\n"
        + "            },\n"
        + "            {\n"
        + "                \"author_id\":\"\",\n"
        + "                \"follow_cnt\":167,\n"
        + "                \"fans_cnt\":307,\n"
        + "                \"works_cnt\":2823,\n"
        + "                \"praised_cnt\":1764,\n"
        + "                \"forward_cnt\":1415,\n"
        + "                \"comment_cnt\":9352,\n"
        + "                \"time\":1665249277\n"
        + "            },\n"
        + "            {\n"
        + "                \"praised_cnt\":1805,\n"
        + "                \"forward_cnt\":1425,\n"
        + "                \"comment_cnt\":9418,\n"
        + "                \"time\":1665567111,\n"
        + "                \"author_id\":\"\",\n"
        + "                \"follow_cnt\":167,\n"
        + "                \"fans_cnt\":304,\n"
        + "                \"works_cnt\":2844\n"
        + "            }\n"
        + "        ]";

    String s1 = "ss";

    JsonArrayGetLast jsonArrayGetLast = new JsonArrayGetLast();

    String evaluate = jsonArrayGetLast.evaluate(s,"1111");

    System.out.println(evaluate);

  }

}
