INSERT INTO dim.dim_author_scd_hourly
SELECT md5(concat(cast(A.source as varchar), A.author_id)) md5_author_id,
       A.author_id,
       A.source,
       A.avatar,
       A.account,
       A.name,
       A.is_certified,
       A.home_page,
       A.identify,
       A.officially,
       A.officially_type,
       A.officially_details,
       A.intro,
       A.sign,
       A.age,
       A.birthday,
       A.area,
       A.gender,
       A.industry,
       A.brand_cooperation,
       A.company,
       A.email,
       A.school,
       A.website,
       B.kol_level,
       B.gc_type,
       A.category,
       A.tags,
       A.has_shop,
       A.has_live,
       A.ip_location,
       A.mcn,
       A.level,
       IF(C.country = '', null, C.country)                 country,
       IF(C.province = '', null, C.province)               province,
       IF(C.city = '', null, C.city)                       city,
       A.follow_cnt,
       A.fans_cnt,
       A.works_cnt,
       A.music_cnt,
       A.praised_cnt,
       A.forward_cnt,
       A.comment_cnt,
       A.ctime,
       A.mtime
FROM (
         SELECT *,
                row_number() over (partition by author_id,source order by mtime desc) rn
         FROM dwd.dwd_mip_author_detail_inc_hourly
         WHERE dt = '${dt}'
           AND hour = '${hour}'
     ) A
         LEFT JOIN dim.dim_kol_level B
                   ON A.fans_cnt >= B.min_num
                       AND A.fans_cnt <= max_num
                       AND A.source = B.source
         LEFT JOIN dim.china_area_none_region C
                   ON (C.city LIKE concat('%', A.ip_location, '%') AND
                       C.province NOT LIKE concat('%', A.ip_location, '%'))
                       OR (C.province LIKE concat('%', A.ip_location, '%') AND C.city = '')
WHERE A.rn = 1
ON CONFLICT(md5_author_id) DO UPDATE
SET author_id = EXCLUDED.author_id,
    source = EXCLUDED.source,
    avatar = EXCLUDED.avatar,
    account = EXCLUDED.account,
    name = EXCLUDED.name,
    is_certified = EXCLUDED.is_certified,
    home_page = EXCLUDED.home_page,
    identify = EXCLUDED.identify,
    officially = EXCLUDED.officially,
    officially_type = EXCLUDED.officially_type,
    officially_details = EXCLUDED.officially_details,
    intro = EXCLUDED.intro,
    sign = EXCLUDED.sign,
    age = EXCLUDED.age,
    birthday = EXCLUDED.birthday,
    area = EXCLUDED.area,
    gender = EXCLUDED.gender,
    industry = EXCLUDED.industry,
    brand_cooperation = EXCLUDED.brand_cooperation,
    company = EXCLUDED.company,
    email = EXCLUDED.email,
    school = EXCLUDED.school,
    website = EXCLUDED.website,
    kol_level = EXCLUDED.kol_level,
    gc_type = EXCLUDED.gc_type,
    category = EXCLUDED.category,
    tags = EXCLUDED.tags,
    has_shop = EXCLUDED.has_shop,
    has_live = EXCLUDED.has_live,
    ip_location = EXCLUDED.ip_location,
    mcn = EXCLUDED.mcn,
    level = EXCLUDED.level,
    country = EXCLUDED.country,
    province = EXCLUDED.province,
    city = EXCLUDED.city,
    follow_cnt = EXCLUDED.follow_cnt,
    fans_cnt = EXCLUDED.fans_cnt,
    works_cnt = EXCLUDED.works_cnt,
    music_cnt = EXCLUDED.music_cnt,
    praised_cnt = EXCLUDED.praised_cnt,
    forward_cnt = EXCLUDED.forward_cnt,
    comment_cnt = EXCLUDED.comment_cnt,
    ctime = EXCLUDED.ctime,
    mtime = EXCLUDED.mtime